-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bank_accounts
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    user_handle character varying(50) COLLATE pg_catalog."default" NOT NULL,
    bank_id uuid,
    account_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ifsc_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    branch character varying(100) COLLATE pg_catalog."default" NOT NULL,
    balance numeric(15, 2) DEFAULT 10000.00,
    is_primary boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    bank_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bank_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT bank_accounts_bank_id_account_number_key UNIQUE (bank_id, account_number),
    CONSTRAINT bank_accounts_user_handle_key UNIQUE (user_handle)
);

CREATE TABLE IF NOT EXISTS public.banks
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    bank_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    CONSTRAINT banks_pkey PRIMARY KEY (id),
    CONSTRAINT banks_bank_name_key UNIQUE (bank_name)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    user_id uuid,
    type character varying(50) COLLATE pg_catalog."default",
    title character varying(100) COLLATE pg_catalog."default",
    message text COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    sender_id uuid,
    sender_handle character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sender_bank_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sender_account_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    receiver_id uuid,
    receiver_handle character varying(50) COLLATE pg_catalog."default" NOT NULL,
    receiver_bank_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    receiver_account_no character varying(50) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(15, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'SUCCESS'::character varying,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    order_id character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (id),
    CONSTRAINT transactions_order_id_key UNIQUE (order_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    aadhar_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    mpin character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_aadhar_number_key UNIQUE (aadhar_number),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_key UNIQUE (phone)
);

ALTER TABLE IF EXISTS public.bank_accounts
    ADD CONSTRAINT bank_accounts_bank_id_fkey FOREIGN KEY (bank_id)
    REFERENCES public.banks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.bank_accounts
    ADD CONSTRAINT bank_accounts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS one_primary_bank_account_per_user
    ON public.bank_accounts(user_id);


ALTER TABLE IF EXISTS public.bank_accounts
    ADD CONSTRAINT fk_bank_name_reference FOREIGN KEY (bank_name)
    REFERENCES public.banks (bank_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_receiver_id_fkey FOREIGN KEY (receiver_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT transactions_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;